### PR TITLE
feat: Allow top-level content pages.

### LINKED ISSUE #27: Enable first level pages
If a first level item in the table of contents has no second level item it should be clickable and it should point to a page. For example on the current website we do not need "Overview" around "Welcome" and "Getting Started" but we would need these last two to be a first level item and they should point to the respective pages.

### PR DESCRIPTION
**Pull request by bwinton**
* To make a page at the top level, just include a `file` key and no `pages` key in the `index.json`
* Note: The links for top-level pages are styled like the other links.  Maybe we (@aminalhazwani) want to change that in a future push. :wink:

Fixes #27.

### CODE REVIEW

**Comment by ericawright** [comment]
Works as described. Interesting that I added a page to "Copy" and it was auto-styled like the lower-level links. I also expect that should be changed.

**Comment by bwinton** [comment]
Yeah, I think I'm going to land this, and let Amin fix the styling in a followup.  :wink:

**Comment by aminalhazwani** [comment]
@bwinton yes, would love to follow up on styling but currently I cannot distinguish the classes applied to `<Link>` when is a `<Page>` or a `<ListItem>`. The classes applied to a `<Page>` should be `fw5 ma0 pv2 near-black` cc @ericawright

**Comment by bwinton** [comment]
In the old style guide, it would be ".section > a.subitem" vs. ".section > a.item", but we seem to have switched away from semantic class names, so I'm not sure if you can make that distinction anymore…  :cry:

I'll see if I can change the code to add the style-based classes only when they're relevant, but I'm doing it under duress, because this seems like a bad way of using css and html.

**Comment by aminalhazwani** [comment]
Thank you @bwinton, very appreciated! I would love to discuss more about CSS approaches with you. Let's follow up on that 😉

**Pull request merged**
